/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package printscript

import java.io.File
import kotlin.test.Test

class AppTest {
    @Test
    fun testBasic() {
        App().execute(
            File("/home/jorge/IdeaProjects/PrintScript/app/src/test/resources/basic_test.pr"),
            "1.0",
            Emitter(),
            ErrorHandle(),
            Scanner()
        )
    }
}
